apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
  namespace: isc3
spec:
  type: ClusterIP
  selector:
    app: orchestrator
  ports:
    - port: 30333
      targetPort: 5001
      protocol: TCP
