apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
  namespace: isc3
spec:
  type: NodePort
  selector:
    app: orchestrator
  ports:
    - name: api
      protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30333
