apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-deployment
  namespace: isc3
  labels:
    app: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: dij0s/orchestrator:latest
          ports:
            - containerPort: 5001
